---
- name: Install PyCharm Professional
  become: false
  community.general.pacman:
    name: pycharm-professional
    state: present
    executable: yay
    extra_args: "--builddir /tmp/yay"

- name: Install R (optional)
  community.general.pacman:
    name:
      - r
    state: present

- name: Install RStudio (optional)
  become: false
  community.general.pacman:
    name: rstudio-desktop-bin
    state: present
    executable: yay
    extra_args: "--builddir /tmp/yay"

- name: Install database tools
  community.general.pacman:
    name:
      - postgresql
      - mariadb
    state: present

# Uncomment to install mongodb from AUR
# - name: Install mongodb
#   community.general.pacman:
#     name: mongodb
#     state: present
#     executable: yay
#     extra_args: "--builddir /tmp/yay"
#   become: false